default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sigla-dev

test:
  <<: *default
  database: sigla-test

production:
  <<: *default
  database: sigla
