default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DATABASE_HOST"] %>
  user: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sigla-dev

test:
  <<: *default
  database: sigla-test

production:
  <<: *default
  database: sigla
